name: test

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3.4.1
        with:
          node-version: 16.x

      - name: Get npm cache directory
        id: npm-cache
        run: |
          echo "::set-output name=dir::$(npm config get cache)"
      - name: Setup npm cache
        uses: actions/cache@v3
        with:
          path: ${{ steps.npm-cache.outputs.dir }}
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install Dependencies
        run: npm ci || npm install

      - name: Build source
        run: npm run build

      - name: Run the API test
        run: |
          npm run start &
          sleep 5
          curl --fail "http://localhost:8000/v1/link-preview/fetch-data.png?url=https://www.youtube.com" --output /dev/null
          curl --fail "http://localhost:8000/v1/link-preview/fetch-data.json?url=https://www.youtube.com"
          curl --fail "http://localhost:8000/v1/link-preview/download-image?url=https://www.youtube.com/img/desktop/yt_1200.png" --output /dev/null
          kill -9 `lsof -i:8000 -t`
